[[devices]]
id = "eresco_32_mf4_c"
name = "Eresco 32 MF4-C"
info = "тип РА: постоянный\nнапряжение: 5-200 кВ\nдиаметр фокусного пятна: 0.4 х 4.0 мм"
electric_power = 600
kVmaximum = 200.0
mAminimum = 0.5
mAmaximum = 7.5 # по факту 10 мА для 60 кВ
focusDistanceDefault = 700

[[devices.curves]]
name = "80 кВ"
kv = 80
points = [
  [0.5, 2],
  [1.0, 3],
  [1.9, 6],
  [2.55, 10],
  [3.05, 15],
  [3.45, 20],
  [4.0, 30],
  [4.7, 50]
]

[[devices.curves]]
name = "100 кВ"
kv = 100
points = [
  [1.1, 2],
  [2.05, 3],
  [3.6, 6],
  [4.9, 10],
  [5.7, 15],
  [6.5, 20],
  [7.45, 30],
  [8.65, 50]
]

[[devices.curves]]
name = "120 кВ"
kv = 120
points = [
  [3.0, 2],
  [4.3, 3],
  [6.5, 6],
  [8.2, 10],
  [9.4, 15],
  [10.45, 20],
  [11.8, 30],
  [13.5, 50]
]

[[devices.curves]]
name = "140 кВ"
kv = 140
points = [
  [3.7, 2],
  [5.7, 3],
  [9.0, 6],
  [11.6, 10],
  [13.3, 15],
  [14.9, 20],
  [17.0, 30],
  [19.55, 50]
]

[[devices.curves]]
name = "160 кВ"
kv = 160
points = [
  [6.0, 2],
  [8.35, 3],
  [12.25, 6],
  [15.4, 10],
  [17.4, 15],
  [19.2, 20],
  [21.65, 30],
  [24.6, 50]
]

[[devices.curves]]
name = "180 кВ"
kv = 180
points = [
  [7.4, 2],
  [10.35, 3],
  [15.2, 6],
  [19.0, 10],
  [21.6, 15],
  [23.9, 20],
  [26.85, 30],
  [30.6, 50]
]

[[devices.curves]]
name = "200 кВ"
kv = 200
points = [
  [11.1, 2],
  [14.2, 3],
  [19.45, 6],
  [23.55, 10],
  [26.3, 15],
  [28.8, 20],
  [31.9, 30],
  [36.0, 50]
]

[[devices]]
id = "arina_9"
name = "АРИНА-9"
info = "тип РА: импульсный\nнапряжение: 300 кВ\nдиаметр фокусного пятна: 2.5 мм"
electric_power = 300
kVmaximum = 300
mAminimum = 1
mAmaximum = 1
focusDistanceDefault = 700

[[devices.curves]]
name = "d7"
kv = 300
points = [
  [4.9, 2.0],
  [8.2, 3.0],
  [10.6, 4.0],
  [12.4, 5.0],
  [14.0, 6.0],
  [15.2, 7.0],
  [16.4, 8.0],
  [17.4, 9.0],
  [18.2, 10.0],
  [20.0, 12.5]
]